sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t taskwarrior test

install: true

script:
  - "docker run -v `pwd`:/opt/powerline-taskwarrior:ro taskwarrior"
