name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [2, 3]
    steps:
      - name: Build test image
        uses: docker/build-push-action@v2
        with:
          build-args: "PYTHON_VERSION=${{ matrix.python_version }}"
          file: test/Dockerfile
