name: publish

on:
  push:
    branches:
      - 'master'
    # tags:
    #   - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Tests
        uses: ${{ github.repository }}/.github/workflows/test.yml@${{ github.sha }}

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0

      - name: Release
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish --build --dry-run
