name: test

on:
  - workflow_call
  - push
  - pull_request


jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        python-version: [ "2.7", "3.7", "3.8", "3.9" ]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Taskwarrior
        run: |
          sudo apt-get install -y taskwarrior
          yes yes | task version

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Load cached pip packages
        id: cached-pip-dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-pip-dependencies.outputs.cache-hit != 'true'
        run: pip install .

      - name: List installed packages
        run: pip list

      - name: Test
        run: ./test/test.sh
